workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 21
    scripts:
      - name: Get Flutter Dependencies
        script: |
          flutter pub get
      - name: Build App Bundle and APK
        script: |
          flutter build appbundle --release
          flutter build apk --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      android-signing:
        keystore: ./germplasmx-release.jks
        keystore-password: $KEYSTORE_PASSWORD
        key-alias: germplasmx
        key-password: $KEY_PASSWORD
