workflows:
  android-release:
    name: Android Release Build (AAB for Play Store)
    max_build_duration: 60
    environment:
      flutter: stable
      java: 21
    scripts:
      - name: Get Flutter Dependencies
        script: |
          flutter pub get
      - name: Build Android App Bundle (.aab for Play Store)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - rashidrao7@gmail.com
