workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 21
      android-signing:
        keystore: ./germplasmx-release.jks   # path relative to repo root
        keystore-password: $KEYSTORE_PASSWORD # store this as an environment variable
        key-alias: germplasmx
        key-password: $KEY_PASSWORD          # store as env var
    scripts:
      - name: Get Flutter Dependencies
        script: |
          flutter pub get
      - name: Build Android App Bundle & APK
        script: |
          flutter build appbundle --release
          flutter build apk --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/flutter-apk/app-release.apk
